### ISSUE TITLE
about page

### ISSUE THREAD

**Issue by juliehenrydesign** [juliehenrydesign/Causes_Site#15]
I'm not sure if the file i'm looking at is what you worked on. did you fix the about page or is it still under construction?

**Comment by aspencerpsu** [comment]
It's still under construction, I can't fix the table to have the borders become adjoined,

the table is completely broken on the second column

**Comment by juliehenrydesign** [comment]
ok. no biggie. I think the whole purpose was the GitHub & I think we nailed that (hopefully)
